.PATH: ${.CURDIR}
KMOD=	bcm2712
SRCS=	bcm2712.c

# Include system headers and generated interface files
SRCS+=	device_if.h bus_if.h pwmbus_if.h opt_fdt.h opt_global.h

# Add system include directories
CFLAGS+= -I/usr/src/sys -I/usr/src/sys/contrib/libfdt -I/usr/src/sys/dev/fdt -I/usr/src/sys/dev/pwm

.include <bsd.kmod.mk>